- app/models/crime.rb
- app/models/order.rb
- app/models/user.rb
- app/views/layouts/application.html.erb
- app/views/shared/_alerts.html.erb
- config/initializers/devise.rb
- config/routes.rb
- db/migrate/20201116150849_devise_create_users.rb
- db/migrate/20201116151245_create_crimes.rb
- db/migrate/20201116151409_create_orders.rb
- db/migrate/20201116152549_change_order_boolean_default.rb
- db/schema.rb
- test/models/crime_test.rb
- test/models/order_test.rb
- test/models/user_test.rb
> models creation

- app/views/devise/confirmations/new.html.erb
- app/views/devise/mailer/confirmation_instructions.html.erb
- app/views/devise/mailer/email_changed.html.erb
- app/views/devise/mailer/password_change.html.erb
- app/views/devise/mailer/reset_password_instructions.html.erb
- app/views/devise/mailer/unlock_instructions.html.erb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_error_messages.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/devise/unlocks/new.html.erb
add views for sign up and sign in + modify registration edit to add alias description and job title
> add sign in up out + edit user model via devise

- app/controllers/application_controller.rb
add strong params to user for devise
> add strong params to device

- app/controllers/pages_controller.rb
Skip autenticate user for home page. Should repare prod
> skip autenticate for home page

- app/controllers/crimes_controller.rb
- app/models/crime.rb
- app/views/crimes/index.html.erb
- app/views/crimes/new.html.erb
- config/routes.rb
- test/controllers/crimes_controller_test.rb
- added the routes for crimes
- added controller page and methods: index, new, create
- added the crimes index and new pages
- tested the creation
> New crimes

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_index.scss
- app/controllers/users_controller.rb
- app/views/users/index.html.erb
- config/routes.rb
- test/controllers/users_controller_test.rb
> Addind users controller

- app/models/user.rb
> comment uniqueness on Alias to solve sign up problem

- app/controllers/crimes_controller.rb
- db/seeds.rb
Added `redirect_to user_path(current_user)` to `CrimesController`
> redirect to user show after new crime

- app/controllers/users_controller.rb
- app/views/users/index.html.erb
I put the filter logic on the view, but maybe we should put it directly on the Controller, what do you think ?
> filter users index on users with crimes

- app/controllers/pages_controller.rb
- app/controllers/users_controller.rb
- added redirect_to /users on home method
- added `skip_before_action :authenticate_user!, only: [:index, :show]` on `UsersController`
> added skip authenticate user befor :index and :show of users

- .gitignore
- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/models/user.rb
- app/views/devise/registrations/new.html.erb
- app/views/users/show.html.erb
- config/environments/development.rb
- config/environments/production.rb
- config/storage.yml
- db/migrate/20201117112632_create_active_storage_tables.active_storage.rb
- db/schema.rb
Add photo to sign up and show of a user
+ setup Cloudinary and Active Storage => You need to bundle install
> Skip alias uniqueness

- app/controllers/crimes_controller.rb
- app/controllers/orders_controller.rb
- app/views/orders/index.html.erb
- app/views/orders/new.html.erb
- app/views/users/show.html.erb
- config/routes.rb
- test/controllers/orders_controller_test.rb
- added orders controller
- added index for order displaying only orders for current user
- added new and create for order nested in crime
- updated user page with "order crime" button
> order controller, new, create and index

- app/views/shared/_navbar.html.erb
added link to my profile
added link to add crime
added link to users index
added link to my orders
> updated navbar

- app/controllers/crimes_controller.rb
- app/views/crimes/edit.html.erb
- app/views/crimes/index.html.erb
- config/routes.rb
> Edit & Delete Crime

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/assets/stylesheets/config/_colors.scss
- app/assets/stylesheets/config/_fonts.scss
- app/views/users/show.html.erb
- Adding banner
- Creating cards for crimes
- Adding new crime button
> Design show page

- app/controllers/users_controller.rb
- app/views/users/index.html.erb
- config/routes.rb
Filter works but need to add dropdown linked to CATEGORIES
> Crime filter

- app/controllers/application_controller.rb
- app/controllers/orders_controller.rb
- app/views/orders/missions.html.erb
- app/views/shared/_navbar.html.erb
- config/routes.rb
added a mission method for orders controller to display the crimes I have to make as a villain
Display in 4 categories
- Crimes to accept - Added PATCH to accept and have order.accepted = true
- Crimes to do - Added PATCH to accept and have order.done = true
- Crimes finished - Added PATCH to accept and have order.paid = true
- Crimes paid and archived
> I can view and edit my crimes

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_texts.scss
- app/views/crimes/edit.html.erb
- app/views/users/index.html.erb
> Color changed for the fonts

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_forms.scss
- app/assets/stylesheets/components/_index.scss
- app/views/users/index.html.erb
- Banner full height
- Cards in container
- Filters text in white
> Fixed homepage styles

- app/assets/stylesheets/components/_banner.scss
- app/views/orders/index.html.erb
> convert ongoing orders into cards

- app/models/user.rb
- app/views/layouts/application.html.erb
- app/views/users/show.html.erb
- db/migrate/20201118112503_add_rating_to_users.rb
- db/schema.rb
Add rating to user model and stars to the show (fontawsome skull not working...)
> User rating

- app/controllers/orders_controller.rb
- app/views/orders/index.html.erb
- app/views/orders/missions.html.erb
- config/routes.rb
- db/migrate/20201118110006_add_dates_to_orders.rb
- db/schema.rb
- added cancel boolean in orders
- added requested_date in orders
- added done_date in orders
- added button to cancel orders
- added display of dates in mission cards
- added display of statuses in order cards
> cancel order & group of orders

- app/assets/stylesheets/components/_navbar.scss
- app/views/shared/_navbar.html.erb
> Styling navbar

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_card.scss
- app/views/users/index.html.erb
> Updating index page

- app/assets/stylesheets/components/_navbar.scss
- app/views/shared/_navbar.html.erb
- Logo link to home
- Sticky navbar
> Navbar update

- app/controllers/application_controller.rb
- app/controllers/users_controller.rb
- app/models/user.rb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/shared/_navbar.html.erb
- app/views/users/index.html.erb
- app/views/users/show.html.erb
- db/migrate/20201119105611_add_adress_to_user.rb
- db/migrate/20201119112517_remove_rating_from_users.rb
- db/schema.rb
- Remove column rating 
- Add column address
- Add attached profile_pic
- Add attached cover_pic
- Update Registration new + Edit forms
- Fix average ratings compute bug
> UserModelUpdate

- app/views/orders/new.html.erb
Added info in the order creation page
> added info about crime at order creation

- app/views/orders/missions.html.erb
- app/views/shared/_navbar.html.erb
Added a modal for all missions cards to see instruction details
> display modal of missions details

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/application.scss
- app/controllers/application_controller.rb
- app/controllers/users_controller.rb
- app/javascript/packs/application.js
- app/javascript/plugins/init_mapbox.js
- app/models/user.rb
- app/views/users/index.html.erb
- config/initializers/geocoder.rb
- db/migrate/20201119115008_add_coordinates_to_users.rb
- db/schema.rb
- package.json
- yarn.lock
> Geo coder Init

- app/views/users/index.html.erb
> Index cards fixed

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_users.scss
- app/views/users/index.html.erb
- Modifying map on index : split screen
> Index splitted with Cards/Map

- app/assets/stylesheets/components/_forms.scss
- app/views/crimes/edit.html.erb
- app/views/crimes/new.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
> add margin to forms

- app/views/orders/missions.html.erb
- app/views/shared/_navbar.html.erb
> Fixed badges position

- app/assets/stylesheets/components/_filter.scss
- app/views/users/index.html.erb
- Centering buttons
- Adding over effect on filters
> Filters updated

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_users.scss
- app/assets/stylesheets/config/_fonts.scss
- app/views/orders/index.html.erb
- app/views/orders/missions.html.erb
- Adding margin over some titles
- Add more contrast to the font as recommended by the TA
> Fix margin mymissions title

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_users.scss
- app/assets/stylesheets/config/_fonts.scss
> texture added

- app/views/orders/missions.html.erb
> flex item wrap on mission cards

- app/assets/stylesheets/components/_card.scss
- app/views/users/index.html.erb
- Better grid layout for the villains
- Responsive for the title
> refacto grid layout + responsive title

- app/assets/stylesheets/components/_card.scss
- app/controllers/orders_controller.rb
- app/views/orders/index.html.erb
- app/views/orders/missions.html.erb
- config/routes.rb
changed look of cards
added buttons to cards (missions and orders)
added "refuse order option"
> changed cards looks

- app/assets/stylesheets/components/_navbar.scss
> Navbar hover text color change

- app/controllers/application_controller.rb
- app/controllers/orders_controller.rb
- app/controllers/users_controller.rb
- app/views/shared/_navbar.html.erb
- app/views/users/_info_window.html.erb
Could not easily calculate current mission requests and display it in header, will do it at the end if I have time remaining.
> Order counts

- app/assets/stylesheets/components/_navbar.scss
small correction to avoid desapearance of button in navbar when hover
> correction of hover to work only in drop down and not in navbar

- app/views/users/show.html.erb
prevent user from adding crime for other user's page
prevent user from ordering own crime
changed display of reviews with star icons
> removed button when wrong user and changed the display of reviews

- app/assets/stylesheets/components/_card.scss
- app/views/users/index.html.erb
> Remove text deco on user cards

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_profile.scss
- app/views/users/show.html.erb
> Adding profile pic on the show + adding box shadows and transitions on index cards

- app/controllers/users_controller.rb
- app/views/users/index.html.erb
Stay to the filter when using or clear filter
> Anchor filter

- app/views/shared/_navbar.html.erb
> color icon macaron

- app/assets/stylesheets/components/_banner.scss
- app/controllers/users_controller.rb
- app/views/users/show.html.erb
review correction
banner top backrgound position
> correction on review

- app/assets/stylesheets/application.scss
- app/javascript/packs/application.js
- app/javascript/plugins/init_star_rating.js
- app/views/orders/index.html.erb
- package.json
- yarn.lock
> Star rating
